
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int pyc = 6;
  public static final int parc = 9;
  public static final int comilla = 17;
  public static final int dobleporc = 2;
  public static final int para = 8;
  public static final int cadena = 15;
  public static final int numero = 13;
  public static final int por = 4;
  public static final int or = 7;
  public static final int igual = 3;
  public static final int EOF = 0;
  public static final int letra = 14;
  public static final int id = 16;
  public static final int simple = 18;
  public static final int error = 1;
  public static final int e_r = 12;
  public static final int llavec = 11;
  public static final int llavea = 10;
  public static final int pnt = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "dobleporc",
  "igual",
  "por",
  "pnt",
  "pyc",
  "or",
  "para",
  "parc",
  "llavea",
  "llavec",
  "e_r",
  "numero",
  "letra",
  "cadena",
  "id",
  "comilla",
  "simple"
  };
}

